#!/usr/bin/env bash
# Script that configures a simple web server
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www//html/index.html
