#!/usr/bin/env bash
# Script that adds http headers to nginx.config
sudo apt -y update
sudo apt -y install nginx
sudo service nginx start
sudo chmod 777 /etc/nginx
sudo chmod 777 /etc/nginx/nginx.conf
sed -i "/sendfile on;/ a \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart